### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by whattila** [BME-MIT-IET/iet-hf2021-just-a-team#1]

**Comment by jancsoadam** [comment]
Elkészítettem a Unit teszteket a Model mappa RDFCollection, RDFContainer, RDFTriple osztályaihoz.
Elkészítettem a Unit teszteket a Model mappa RDFGraph osztályának AddItem, RemoveItem, IsEqual típusú metódusaihoz.

**Comment by jancsoadam** [comment]
Elkészítettem a Unit teszteket a Model mappa RDFGraph osztályának Select, Unreify, Set típusú metódusaihoz.
Elkészítettem a Unit teszteket a Model mappa RDFCollection, RDFResource, RDFPlainLiteral osztályaihoz.
